"""empty message

Revision ID: 53db0270bf11
Revises: 9a8dc8a0e739
Create Date: 2023-03-28 23:17:31.724055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53db0270bf11'
down_revision = '9a8dc8a0e739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('article', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('article', 'dt_created')
    op.drop_column('article', 'dt_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('dt_updated', sa.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('dt_created', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('article', 'updated_at')
    op.drop_column('article', 'created_at')
    # ### end Alembic commands ###
